### ISSUE TITLE
List date for resources

### ISSUE THREAD

**Issue by briandfoy** [thibaultduponchelle/perlres#16]
Although this list aims to be comprehensive, presenting outdated information such as a book from 30 years ago next to more recent stuff is less that helpful. Attaching dates and versions of Perl covered, and ordering by descending date can help people choose the best, most up-to-date resources.

**Comment by thibaultduponchelle** [comment]
First I'm very honored to see you here :blush:

Disclaimer : I have to say that this list is unordered by design and you can find this kind of oddity in all sections... 

...But you’re right book section is particularly a mess and more impacted by this “design” and I’m inclined to do something here.

I think I can try to do something but I think I can’t find Perl version covered by every books. 

I can probably find or guess almost last issue year of each book but I have the feeling that strictly sorting by last issue date will introduce some oddities also.

Maybe I can try to mix both last issue date and book fame (biaised) and order by “period” (either something like “legacy perl period”, “modern perl period” and “post modern perl period”).
Or just something without period names and short steps of 3 or 4 years. 

In anycase  I can try to propose something to arrange a bit this books list and be more helpful than only comprehensive

If you have any suggestion about what I just said or anything please share :)

**Comment by thibaultduponchelle** [comment]
Actually I can start first by trying to do a prototype with strict last issue date sorting and see what it looks like.

Concerning Perl covered version, do we really have recent books that covers old Perl version ?

**Comment by thibaultduponchelle** [comment]
Hello @briandfoy 

I fixed it 😃 

[Ordered books](https://github.com/thibaultduponchelle/perlres/blob/master/README.md#books-books)
